export * from "./Tarjeta";
export * from "./ListadoMarca";
export * from "./Modal";
export * from "./ImagenesPortada";
export * from "./InfoGrafia";
export * from "./Tienda";
export * from "./Header";
export * from "./ImgGarantia";
export * from "./Footer";
export * from "./Carruseles";
export * from "./ImagenZoom";
export * from "./ModalPregunta";
export { default as SetAlerta } from "./SetAlerta";
